name: "Pull Submodules"

on:
  schedule:
    - cron: "18 12 * * 2"

jobs:
  pull:
    name: Pull Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
